### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by justindbms** [justindbms/evaluation-system#9]
**Things to do:**
- pano flow natin sa "new and improved for accountability" na score tally para sa principal? same page?
- lalagyan ko pa ng percentages yung... percentages
- yung search by section, di fool-proof yun.
- export ratings report
- transfer yung score mula sa score page into sa main.
- may idea ba tungkol sa pag-access sa mga archived na final ratings (as in yung final). Yung standard questionnaire scores pwedeng sa main lang din eh. kaya bang parang pagination? hehe
- i-pupush ba natin yung 'wish' (gagawing parang grid/excel yung sa principal kasi marami). kelangan ko ng input mo dito kasi _shit_.

**Comment by justindbms** [comment]
**Updated Things to do**
- okay na yung "new and improved for accountability". bale para mas madaling matrace, siguro lagyan nalang ng parang sort by function
- percentages
- search by section will fail (for removal/modification nalang siguro)
- export ratings report
- transfer yung score mula sa score page into sa main.
- done
- i-pupush ba natin yung 'wish' (gagawing parang grid/excel yung sa principal kasi marami). kelangan ko ng input mo dito kasi shit.

**Comment by justindbms** [comment]
**Updated Things To Do**
ME:
1. archive backend layout
2. csv handler for user creation/editing sections
3. rework search by section
4. revise user manual
5. spreadsheet style for principal questionnaires (low priority)

MARCI:
1. export button after title (balak ko after ng title na "Final Rating, Questionaire rating" para alam kung anong form i-export to csv
2. export (ako na dito kc iexport ko lang naman ung table papuntang csv)
3. past score layout (and archive score layout)
4. filter questionnaire (low priority)
5. confirm prompts i.e. "are you sure <do something>"

**Comment by MarceloAnzano** [comment]
# **Todo Marci!!**
- [x]  Margin, eval
- [x]  Icons, local
- [x]  archive account
- [x]  dropdown eval score
  - js error check eval
    -increment 0.5
    -tooltip shit
- [x]  Past score
  -past score title
  -decimal places
- [x]  Accordion (Setting)
- [ ]  Ratings, verbal rating, add column (filter)
- [ ]  _captcha submit
  -security check_

# **Todo Justin!!**
- [x]  Evaluation, stl self
- [x]  Evaluation, multiple subjects
- [ ]  Students comments
- [x]  Self edit for setting
- [x]  Fetch users
- [x]  _Audit trail SHIIIT!! (Logging)_
- [x]  Forget  password
  -How many tries 7
- [ ]  _captcha submit
  -security check_

**Comment by MarceloAnzano** [comment]
# ** Todo @arian0987 ** #

- [ ] Another row  for student number, replace "student ID" with "RFID code"
- [ ] Update record id not delete
- [ ] Reported lost ID. Di idedelete  (History)
- [ ] 24 hours
- [ ] Tap restrictions (interval i.e. 5 mins)
